// Greater Sydney LGAs (ABS Greater Capital City Statistical Area boundary composition, 2024+)
// Fields: lga, council, short, domain, expectedOrgHints
export const LGAS = [
  { lga:'Sydney', council:'City of Sydney Council', short:'Sydney', domain:'cityofsydney.nsw.gov.au' },
  { lga:'Blacktown', council:'Blacktown City Council', short:'Blacktown', domain:'blacktown.nsw.gov.au' },
  { lga:'Cumberland', council:'Cumberland Council', short:'Cumberland', domain:'cumberland.nsw.gov.au' },
  { lga:'Parramatta', council:'Parramatta Council', short:'Parramatta', domain:'parramatta.nsw.gov.au' },
  { lga:'Canterbury-Bankstown', council:'Canterbury-Bankstown Council', short:'Canterbury-Bankstown', domain:'cbc.nsw.gov.au' },
  { lga:'Georges River', council:'Georges River Council', short:'Georges River', domain:'georgesriver.nsw.gov.au' },
  { lga:'Bayside', council:'Bayside Council', short:'Bayside', domain:'bayside.nsw.gov.au' },
  { lga:'Northern Beaches', council:'Northern Beaches Council', short:'Northern Beaches', domain:'northernbeaches.nsw.gov.au' },
  { lga:'Sutherland', council:'Sutherland Shire Council', short:'Sutherland', domain:'sutherland.nsw.gov.au' },
  { lga:'Hornsby', council:'Hornsby Shire Council', short:'Hornsby', domain:'hornsby.nsw.gov.au' },
  { lga:'Ryde', council:'City of Ryde', short:'Ryde', domain:'ryde.nsw.gov.au' },
  { lga:'Penrith', council:'City of Penrith', short:'Penrith', domain:'penrithcity.nsw.gov.au' },
  { lga:'Hawkesbury', council:'Hawkesbury City Council', short:'Hawkesbury', domain:'hawkesbury.nsw.gov.au' },
  { lga:'Strathfield', council:'Strathfield Council', short:'Strathfield', domain:'strathfield.nsw.gov.au' },
  { lga:'Marrickville', council:'Marrickville Council', short:'Marrickville', domain:'marrickville.nsw.gov.au' },
  { lga:'Manly', council:'Manly Council', short:'Manly', domain:'manly.nsw.gov.au' },
  { lga:'Randwick', council:'Randwick City Council', short:'Randwick', domain:'randwick.nsw.gov.au' },
  { lga:'Woollahra', council:'Woollahra Municipal Council', short:'Woollahra', domain:'woollahra.nsw.gov.au' },
  { lga:'Waverley', council:'Waverley Council', short:'Waverley', domain:'waverley.nsw.gov.au' },
  { lga:'Lane Cove', council:'Lane Cove Council', short:'Lane Cove', domain:'lanecove.nsw.gov.au' },
  { lga:'Willoughby', council:'City of Willoughby', short:'Willoughby', domain:'willoughby.nsw.gov.au' },
  { lga:'Ku-ring-gai', council:'Ku-ring-gai Council', short:'Ku-ring-gai', domain:'krg.nsw.gov.au' },
  { lga:'Mosman', council:'Mosman Council', short:'Mosman', domain:'mosman.nsw.gov.au' },
  { lga:'Hunters Hill', council:'Hunters Hill Council', short:'Hunters Hill', domain:'huntershill.nsw.gov.au' },
  { lga:'Fairfield', council:'Fairfield City Council', short:'Fairfield', domain:'fairfieldcity.nsw.gov.au' },
  { lga:'Liverpool', council:'City of Liverpool', short:'Liverpool', domain:'liverpool.nsw.gov.au' },
  { lga:'Camden', council:'Camden Council', short:'Camden', domain:'camden.nsw.gov.au' },
  { lga:'Campbelltown', council:'Campbelltown City Council', short:'Campbelltown', domain:'campbelltown.nsw.gov.au' },
  { lga:'Northern Beaches (n/a)', council:'', short:'', domain:'' },
].filter(x=>x.council);
